{
 "title": "antmediaserver",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of WebRTC Viewer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1113",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1111",
       "field": "localWebRTCViewers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of HLS Viewer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1035",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1033",
       "field": "localHLSViewers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total WebRTC Viewers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1489",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1487",
       "field": "localWebRTCViewers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total HLS Viewers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1571",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1569",
       "field": "localHLSViewers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Percentiles Cpu Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "cpuUsage.systemCPULoad",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "25",
         "50",
         "75",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Instance CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instanceId.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "cpuUsage.systemCPULoad",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total WebRTC Live Streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1329",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1327",
       "field": "localWebRTCLiveStreams",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:160",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:158",
       "field": "instanceId.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Local WebRTC Viewers Group By Instance Id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instanceId.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "localWebRTCViewers",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "systemMemoryInfo.freeMemory",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System In Use Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instanceId.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "systemMemoryInfo.inUseMemory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM In Use Native Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instanceId.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvmNativeMemoryUsage.inUseMemory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JVM Native Max Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "instanceId.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "jvmNativeMemoryUsage.maxMemory",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Video Frame Send Period",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "video_frame_send_period",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Audio Frame Send Period",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "audio_frame_send_period",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fileSystemInfo.freeSpace",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         25,
         50,
         75,
         95,
         99
        ]
       },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}