apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ant-media-server-edge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ant-media-server-edge
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
