apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ant-media-server-origin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ant-media-server-origin
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
