apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
    component: elasticsearch
    release: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      component: elasticsearch
      release: elasticsearch
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
        component: elasticsearch
        release: elasticsearch
    spec:
      containers:
        - env:
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: bootstrap.memory_lock
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          securityContext:
            privileged: true
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      initContainers:
        - command:
            - sh
            - -c
            - chown -R 1000:1000 /usr/share/elasticsearch/data
            - sysctl -w vm.max_map_count=262144
            - chmod 777 /usr/share/elasticsearch/data
            - chmod 777 /usr/share/elasticsearch/data/node
            - chmod g+rwx /usr/share/elasticsearch/data
            - chgrp 1000 /usr/share/elasticsearch/data
          image: busybox:1.29.2
          imagePullPolicy: IfNotPresent
          name: set-dir-owner
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      restartPolicy: Always
      securityContext: {}

      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data


