apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 7.x
      timeField: "@timestamp"
    secureJsonData:
      username: admin
      password: admin
