# This Docker file run Ant Media Server as a service. 
# It's not the recommend way for running docker containers. 
# However this approach let us test some cases  

FROM ubuntu:18.04

ARG AntMediaServer
ARG MongoDBServer=
ARG MongoDBUsername=
ARG MongoDBPassword=

ARG BranchName=master

#Running update and install makes the builder not to use cache which resolves some updates
RUN apt-get update && apt-get install -y curl libcap2 wget net-tools

ADD ./${AntMediaServer} /home

RUN cd home \
    && pwd \
    && wget https://raw.githubusercontent.com/ant-media/Scripts/${BranchName}/install_ant-media-server.sh \
    && chmod 755 install_ant-media-server.sh

RUN cd home \
    && pwd \
    && ./install_ant-media-server.sh ${AntMediaServer}


RUN /bin/bash -c 'if [ ! -z "${MongoDBServer}" ]; then \
                    /usr/local/antmedia/change_server_mode.sh cluster ${MongoDBServer} ${MongoDBUsername} ${MongoDBPassword}; \
                 fi'

ENTRYPOINT service antmedia start && /bin/bash
