name: AlmaLinux
on: [push]

jobs:
  Almalinux8:
    runs-on: ubuntu-20.04
    container: almalinux:8
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-almalinux
  Almalinux9:
    runs-on: ubuntu-20.04
    container: almalinux:9
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-almalinux-9

