name: AlmaLinux
on: [push]

jobs:

  Almalinux8:
    runs-on: ubuntu-24.04
    container: almalinux:8
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-almalinux-8

  Almalinux9:
    runs-on: ubuntu-24.04
    container: almalinux:9
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-almalinux-9

