name: Ant Media Server Automation Actions

on: [push]

#on:
#  schedule:
#    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC

jobs:
  mongodb_install_ubuntu_20_04:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up MongoDB
        run: |
          bash ./install_mongodb.sh
  mongodb_install_ubuntu_22_04:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up MongoDB
        run: |
          bash ./install_mongodb.sh
  mongodb_install_ubuntu_24_04:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up MongoDB
        run: |
          bash ./install_mongodb.sh