name:  Install v2.4 to Ubuntu 20.04
on: [push]
jobs:
  Install-Ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      #Get latest version
      - run: wget -O ant-media-server-community.zip "https://oss.sonatype.org/service/local/repositories/releases/content/io/antmedia/ant-media-server/2.4.3/ant-media-server-2.4.3-community.zip";
      - run: ./install_ant-media-server.sh -i ant-media-server-community.zip
      - run: sleep 30
      - run: cat /usr/local/antmedia/log/ant-media-server.log
      - run: |
         if [ $(cat /usr/local/antmedia/log/ant-media-server.log | grep "LiveApp started" | wc -l | xargs) -eq 0 ]; then 
           echo "LiveApp started log does not exist. Check the logs above"
           exit 1;
         fi;
      - run: cat /usr/local/antmedia/log/antmedia-error.log
