name: Test MongoDB Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-mongodb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: |
          wget https://raw.githubusercontent.com/ant-media/Scripts/3b3fd732613f2e234847231ff2b4c0e36d0440f1/install_mongodb.sh
          ls -alh

      - name: Run MongoDB installation script
        run: bash ./install_mongodb.sh --auto-create 

      - name: Verify MongoDB service
        run: |
          sudo systemctl restart mongod
          sudo systemctl enable mongod
          sleep 5
          systemctl is-active mongod || (echo "MongoDB failed to start" && exit 1)

      - name: Test MongoDB authentication
        run: |
          USERNAME=$(cat /tmp/mongo_credentials.txt | awk '{print $3}' | head -1)
          PASSWORD=$(cat /tmp/mongo_credentials.txt | awk '{print $3}' | tail -1)
          echo "Testing login with user: $USERNAME"
          echo "show dbs" | mongosh --username "$USERNAME" --password "$PASSWORD" --authenticationDatabase admin || (echo "Authentication failed" && exit 1)
